[tool.poetry]
name = "ioccheck"
version = "0.1.0"
description = ""
authors = ["ranguli <hello@joshmurphy.ca>"]

[tool.poetry.dependencies]
python = "^3.7.3"
vt-py = "^0.6.1"
ratelimit = "^2.2.1"
backoff = "^1.10.0"
tabulate = "^0.8.9"
termcolor = "^1.1.0"
click = "^7.1.2"
requests = "^2.25.1"
"hurry.filesize" = "^0.9"
isort = "^5.7.0"
shodan = "^1.25.0"
pyfiglet = "^0.8.post1"
mypy = "^0.812"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "^20.8b1"
flake8 = "^3.8.4"
bandit = "^1.7.0"
nox = "^2020.12.31"
mypy = "^0.812"

[tool.poetry.scripts]
ioccheck = "ioccheck.cli:run"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

